(in-package #:retrodeck)

(defun dashboard-terminal-title (launch-plan)
  (let ((label (getf launch-plan :label)))
    (check-type label string)
    (string-upcase label)))

(defun dashboard-terminal-starting-status (launch-plan)
  (format nil "STARTING ~A" (dashboard-terminal-title launch-plan)))

(defun decode-native-child-result (result)
  (unless (and (listp result) (= (length result) 6))
    (error "Native child result is invalid"))
  (destructuring-bind (started touch exit-code signal error shutdown) result
    (unless (member started '(0 1) :test #'eql)
      (error "Native child started flag is invalid"))
    (unless (member touch '(0 1) :test #'eql)
      (error "Native child touch flag is invalid"))
    (unless (member shutdown '(0 1) :test #'eql)
      (error "Native child shutdown flag is invalid"))
    (unless (and (integerp exit-code)
                 (or (= exit-code -1) (<= 0 exit-code 255)))
      (error "Native child exit code is invalid"))
    (unless (and (integerp signal)
                 (or (= signal -1) (<= 1 signal 255)))
      (error "Native child signal is invalid"))
    (when error
      (check-type error string))
    (when (and (= started 0)
               (or (= touch 1) (= shutdown 1)
                   (not (= exit-code -1)) (not (= signal -1))))
      (error "Native child result describes an unstarted child"))
    (when (and (= touch 1) (= shutdown 1))
      (error "Native child result has both touch and shutdown requests"))
    (when (and (not (= exit-code -1)) (not (= signal -1)))
      (error "Native child result has both an exit code and signal"))
    (list :started (= started 1)
          :exited-for-touch (= touch 1)
          :exit-code (unless (= exit-code -1) exit-code)
          :signal (unless (= signal -1) signal)
          :error error
          :shutdown-requested (= shutdown 1))))

(defun dashboard-terminal-result-status (launch-plan result)
  (let ((title (dashboard-terminal-title launch-plan))
        (error (getf result :error))
        (exit-code (getf result :exit-code))
        (signal (getf result :signal)))
    (cond
      ((and error (plusp (length error)))
       (format nil "~A ERROR - CHECK LOG" title))
      ((not (getf result :started))
       (format nil "~A DID NOT START" title))
      ((getf result :exited-for-touch)
       (format nil "RETURNED FROM ~A" title))
      ((eql exit-code 0)
       (format nil "~A EXITED" title))
      (exit-code
       (format nil "~A EXITED (STATUS ~D)" title exit-code))
      (signal
       (format nil "~A STOPPED (SIGNAL ~D)" title signal))
      (t
       (format nil "~A STOPPED" title)))))

(defun report-dashboard-child-error (result)
  (let ((error (getf result :error)))
    (when (and error (plusp (length error)))
      (format *error-output* "retrodeck: ~A~%" error)
      (finish-output *error-output*)))
  result)

(defun run-dashboard-terminal (launch-plan &optional (finish-sound-p t))
  (let* ((executable (getf launch-plan :executable))
         (arguments (getf launch-plan :arguments))
         (environment (getf launch-plan :environment))
         (label (getf launch-plan :label))
         (keymap (cdr (assoc "RETRO_DECK_KEYMAP" environment :test #'string=))))
    (check-type executable string)
    (check-type label string)
    (unless (and (= (length arguments) 1) (stringp (first arguments)))
      (error "Terminal launch plan needs one mode argument"))
    (check-type keymap string)
    (unless (and (getf launch-plan :touch-supervision)
                 (getf launch-plan :mirror-console))
      (error "Terminal launch plan needs touch supervision and console mirroring"))
    (when finish-sound-p
      (finish-menu-sound))
    (report-dashboard-child-error
     (decode-native-child-result
      (run-terminal (native-path-string executable)
                    (coerce keymap 'base-string)
                    (coerce (first arguments) 'base-string)
                    (coerce label 'base-string))))))

(defun run-dashboard-child (launch-plan)
  (let ((executable (getf launch-plan :executable))
        (arguments (getf launch-plan :arguments))
        (environment (getf launch-plan :environment))
        (label (getf launch-plan :label))
        (touch-supervision (getf launch-plan :touch-supervision)))
    (check-type executable string)
    (check-type arguments list)
    (check-type environment list)
    (check-type label string)
    (unless (member touch-supervision '(nil t) :test #'eq)
      (error "Child launch plan touch supervision flag is invalid"))
    (when (getf launch-plan :mirror-console)
      (error "Generic child launch plans cannot mirror the console"))
    (let ((native-arguments
            (mapcar (lambda (argument)
                      (check-type argument string)
                      (coerce argument 'base-string))
                    arguments))
          (native-environment
            (mapcar (lambda (binding)
                      (unless (and (consp binding)
                                   (stringp (car binding))
                                   (stringp (cdr binding)))
                        (error "Child launch environment is invalid"))
                      (cons (coerce (car binding) 'base-string)
                            (coerce (cdr binding) 'base-string)))
                    environment)))
      (report-dashboard-child-error
       (decode-native-child-result
        (run-child (native-path-string executable)
                   native-arguments native-environment
                   (coerce label 'base-string)
                   (if touch-supervision 1 0)))))))

(defun run-dashboard-launch (launch-plan kind)
  (unless (member kind '(:game :terminal :reboot) :test #'eq)
    (error "Unknown dashboard launch kind ~S" kind))
  (let ((result (if (eq kind :terminal)
                    (run-dashboard-terminal launch-plan nil)
                    (run-dashboard-child launch-plan))))
    (list :child-returned
          :shutdown (getf result :shutdown-requested)
          :touch-disconnected (not (getf launch-plan :touch-supervision))
          :result result)))
