(eval-when (:compile-toplevel :load-toplevel :execute)
  (require 'asdf))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (pushnew :hunchentoot-no-ssl *features*)
  #+sbcl (progn (require 'sb-rotate-byte) (require 'sb-bsd-sockets)
                 (require 'sb-posix))
  (asdf:operate 'asdf:load-source-op :hunchentoot)
  (asdf:operate 'asdf:load-source-op :zip))

(defpackage #:retrodeck.uploader
  (:use #:cl)
  (:export #:configure #:start #:stop #:run))

(in-package #:retrodeck.uploader)

(defparameter *source-directory*
  (uiop:pathname-directory-pathname (or *load-truename* *default-pathname-defaults*)))
(defparameter *data-root* #p"/mnt/data/")
(defparameter *native* "/mnt/data/nes-deck/retrodeck-native")
(defparameter *restart-command* '("/etc/init.d/nes-deck" "restart"))
(defparameter *asset-directory* *source-directory*)
(defvar *storage-lock* (bordeaux-threads:make-lock "uploader storage"))
(defparameter *systems*
  '(("nes" ".nes" "#FF5F00" 8388608 :nes)
    ("gb" ".gb" "#87AF87" 8388608 :gb)
    ("gbc" ".gbc" "#5F87D7" 8388608 :gbc)
    ("zx" ".tap" "#AF87D7" 8388608 :zx)
    ("chip8" ".ch8" "#5FD7D7" 65024 :chip8)))
(defparameter *palette-specs*
  '(("background" . "Background") ("text-dark" . "Dark text")
    ("field" . "Field") ("surface" . "Surface")
    ("inactive-border" . "Inactive border") ("control-border" . "Control border")
    ("footer" . "Footer") ("inactive-text" . "Inactive text")
    ("text" . "Text") ("white" . "Bright white") ("title" . "Title")
    ("volume-off" . "Volume off") ("volume-on" . "Volume on")
    ("selected" . "Selected item") ("wifi-active" . "Wi-Fi active")
    ("wifi-focus" . "Wi-Fi focus") ("wifi-active-border" . "Wi-Fi active border")
    ("field-label" . "Field label") ("accent" . "Accent")
    ("active" . "Active control") ("control-surface" . "Control surface")
    ("muted" . "Muted control")))

(define-condition request-error (error)
  ((message :initarg :message :reader request-error-message))
  (:report (lambda (condition stream)
             (write-string (request-error-message condition) stream))))

(defun fail (control &rest arguments)
  (error 'request-error :message (apply #'format nil control arguments)))

(defun configure (&key (data-root *data-root*) native
                       (restart-command *restart-command*)
                       (asset-directory *asset-directory*))
  (setf *data-root* (uiop:ensure-directory-pathname data-root)
        *native* (or native (namestring (merge-pathnames "nes-deck/retrodeck-native"
                                                         *data-root*)))
        *restart-command* restart-command
        *asset-directory* (uiop:ensure-directory-pathname asset-directory)))

(defun data-path (relative)
  (merge-pathnames relative *data-root*))

(defun split (string character)
  (uiop:split-string string :separator (list character)))

(defun text-lines (text)
  (let ((lines (split text #\Newline)))
    (if (and lines (string= (car (last lines)) "")) (butlast lines) lines)))

(defun read-bytes (path maximum &optional missing-ok)
  (unless (probe-file path)
    (if missing-ok (return-from read-bytes nil) (fail "file is missing: ~A" path)))
  (with-open-file (stream path :direction :input :element-type '(unsigned-byte 8))
    (let ((size (file-length stream)))
      (unless (and size (<= 0 size maximum))
        (fail "file exceeds its size limit: ~A" path))
      (let ((bytes (make-array size :element-type '(unsigned-byte 8))))
        (unless (= size (read-sequence bytes stream))
          (fail "file could not be read: ~A" path))
        bytes))))

(defun read-text (path maximum &optional missing-ok)
  (let ((bytes (read-bytes path maximum missing-ok)))
    (when bytes
      (handler-case (babel:octets-to-string bytes :encoding :utf-8)
        (error () (fail "file is not UTF-8: ~A" path))))))

(defun chmod-private (path)
  (uiop:run-program (list "chmod" "600" (namestring path))))

(defun atomic-text (path text)
  (ensure-directories-exist path)
  (let* ((directory (uiop:pathname-directory-pathname path))
         (temporary (merge-pathnames
                     (format nil ".uploader-~36R" (random most-positive-fixnum))
                     directory))
         (installed nil))
    (unwind-protect
         (progn
           (with-open-file (stream temporary :direction :output :if-exists :error
                                            :element-type '(unsigned-byte 8))
             (write-sequence (babel:string-to-octets text :encoding :utf-8) stream))
           (chmod-private temporary)
           (uiop:rename-file-overwriting-target temporary path)
           (setf installed t))
      (unless installed (uiop:delete-file-if-exists temporary)))))

(defun install-rom (path bytes)
  (ensure-directories-exist path)
  (when (probe-file path) (fail "a ROM with this name already exists"))
  (let ((temporary (merge-pathnames
                    (format nil ".rom-upload-~36R" (random most-positive-fixnum))
                    (uiop:pathname-directory-pathname path)))
        (installed nil))
    (unwind-protect
         (progn
           (with-open-file (stream temporary :direction :output :if-exists :error
                                            :element-type '(unsigned-byte 8))
             (write-sequence bytes stream))
           (chmod-private temporary)
           (when (probe-file path) (fail "a ROM with this name already exists"))
           (rename-file temporary path)
           (setf installed t))
      (unless installed (uiop:delete-file-if-exists temporary)))))

(defun restart-dashboard ()
  (when *restart-command*
    (multiple-value-bind (output ignored status)
        (uiop:run-program *restart-command* :output :string :error-output :output
                                            :ignore-error-status t)
      (declare (ignore ignored))
      (unless (zerop status)
        (fail "restart failed with status ~D (~A)" status
              (string-trim '(#\Space #\Tab #\Newline #\Return) output))))))

(defun normalize-rgb (value)
  (when (and (stringp value) (= (length value) 7) (char= (char value 0) #\#)
             (every (lambda (character) (digit-char-p character 16))
                    (subseq value 1)))
    (string-upcase value)))

(defun palette-name-p (name)
  (assoc name *palette-specs* :test #'string=))

(defun validate-palette (values)
  (unless (= (hash-table-count values) (length *palette-specs*))
    (fail "palette must contain every dashboard color exactly once"))
  (dolist (spec *palette-specs* values)
    (let ((value (gethash (car spec) values)))
      (unless (and value (string= value (normalize-rgb value)))
        (fail "palette ~A must use canonical #RRGGBB" (car spec))))))

(defun parse-palette-tsv (text)
  (let ((values (make-hash-table :test #'equal)) (saw-icon nil))
    (dolist (line (text-lines text))
      (let ((fields (split (string-right-trim '(#\Return) line) #\Tab)))
        (unless (= (length fields) 2) (fail "appearance contains a malformed entry"))
        (destructuring-bind (name value) fields
          (cond ((string= name "settings-icon")
                 (when (or saw-icon (not (valid-legacy-icon-p value)))
                   (fail "appearance contains an invalid settings icon"))
                 (setf saw-icon t))
                (t
                 (unless (palette-name-p name) (fail "palette contains an unknown entry"))
                 (when (gethash name values) (fail "palette repeats ~A" name))
                 (setf (gethash name values)
                       (or (normalize-rgb value)
                           (fail "palette ~A is not a full RGB color" name))))))))
    (validate-palette values)))

(defun valid-legacy-icon-p (value)
  (and (stringp value) (<= 1 (length value) 64)
       (every (lambda (character)
                (or (char<= #\a character #\z) (digit-char-p character)
                    (char= character #\-)))
              value)))

(defun palette-form (text)
  (handler-case
      (with-input-from-string (stream text)
        (let ((*read-eval* nil) (eof (gensym)))
          (let ((form (read stream nil eof)))
            (unless (and (not (eq form eof)) (eq (read stream nil eof) eof))
              (fail "appearance override has an invalid structure"))
            form)))
    (request-error (condition) (error condition))
    (error () (fail "appearance override has an invalid structure"))))

(defun parse-palette-override (text)
  (let* ((form (palette-form text))
         (palette (cond
                    ((and (listp form) (= (length form) 4)
                          (equal (subseq form 0 3) '(:version 2 :palette)))
                     (fourth form))
                    ((and (listp form) (= (length form) 6)
                          (equal (subseq form 0 3) '(:version 3 :settings-icon))
                          (valid-legacy-icon-p (fourth form)) (eq (fifth form) :palette))
                     (sixth form))
                    (t (fail "appearance override must use schema version 2 or 3"))))
         (values (make-hash-table :test #'equal)))
    (unless (and (listp palette) (= (length palette) (* 2 (length *palette-specs*))))
      (fail "palette override has an invalid structure"))
    (loop for (key value) on palette by #'cddr
          for name = (and (keywordp key) (string-downcase (symbol-name key)))
          do (unless (and name (palette-name-p name))
               (fail "palette override contains an unknown color"))
             (when (gethash name values) (fail "palette override repeats ~A" name))
             (setf (gethash name values)
                   (or (normalize-rgb value)
                       (fail "palette override ~A is not a full RGB color" name))))
    (validate-palette values)))

(defun current-palette ()
  (let ((base nil) (last-error nil))
    (dolist (path (list (data-path "nes-deck/menu/palette.tsv")
                        (data-path "nes-deck/state/palette.tsv")))
      (handler-case
          (unless base (setf base (parse-palette-tsv (read-text path 4096))))
        (error (condition) (setf last-error condition))))
    (unless base (fail "read installed dashboard appearance: ~A" last-error))
    (handler-case
        (let ((override (read-text (data-path "nes-deck/state/dashboard-palette.sexp")
                                   4096 t)))
          (when override (setf base (parse-palette-override override))))
      (error () nil))
    (mapcar (lambda (spec) (list (car spec) (cdr spec) (gethash (car spec) base)))
            *palette-specs*)))

(defun encode-palette (values)
  (with-output-to-string (stream)
    (format stream "(:version 2~% :palette~%  (")
    (loop for spec in *palette-specs* for index from 0
          do (when (plusp index) (format stream "~%   "))
             (format stream ":~A \"~A\"" (car spec) (gethash (car spec) values)))
    (format stream "))~%")))

(defun %save-palette (values)
  (validate-palette values)
  (atomic-text (data-path "nes-deck/state/dashboard-palette.sexp")
               (encode-palette values))
  (handler-case (restart-dashboard)
    (error (condition)
      (fail "appearance was saved, but the dashboard could not reload: ~A" condition))))

(defun save-palette (values)
  (bordeaux-threads:with-lock-held (*storage-lock*)
    (%save-palette values)))

(defun system-spec (system)
  (or (assoc system *systems* :test #'string=) (fail "choose a supported system")))

(defun valid-title-p (title)
  (and (stringp title) (<= 1 (length title) 64)
       (string= title (string-trim '(#\Space #\Tab #\Newline #\Return #\Page) title))
       (every (lambda (character)
                (let ((code (char-code character)))
                  (not (or (< code 32) (<= 127 code 159)))))
              title)))

(defun slugify (title)
  (string-right-trim
   "-" (with-output-to-string (stream)
         (let ((hyphen nil) (size 0))
           (loop for character across (string-downcase title) while (< size 32)
                 for valid = (or (char<= #\a character #\z) (digit-char-p character))
                 do (cond (valid (write-char character stream) (incf size) (setf hyphen nil))
                          ((and (plusp size) (not hyphen))
                           (write-char #\- stream) (incf size) (setf hyphen t))))))))

(defparameter *nintendo-logo*
  #(206 237 102 102 204 13 0 11 3 115 0 131 0 12 0 13
    0 8 17 31 136 137 0 14 220 204 110 230 221 221 217 153
    187 187 103 99 110 14 236 204 221 220 153 159 187 185 51 62))

(defun validate-rom (system bytes)
  (let* ((spec (system-spec system)) (size (length bytes)))
    (unless (<= 1 size (fourth spec))
      (fail "the ROM must contain 1 through ~D bytes" (fourth spec)))
    (ecase (fifth spec)
      (:nes (unless (and (>= size 16) (equalp (subseq bytes 0 4) #(78 69 83 26)))
              (fail "the file has no iNES header")))
      ((:gb :gbc)
       (unless (and (>= size #x150) (equalp (subseq bytes #x104 #x134) *nintendo-logo*))
         (fail "the file has no valid Game Boy header"))
       (let ((checksum 0))
         (loop for index from #x134 to #x14c
               do (setf checksum (mod (- checksum (aref bytes index) 1) 256)))
         (unless (= checksum (aref bytes #x14d))
           (fail "the Game Boy header checksum is invalid")))
       (when (and (eq (fifth spec) :gbc) (not (member (aref bytes #x143) '(#x80 #xc0))))
         (fail "the ROM does not advertise Game Boy Color support")))
      (:zx
       (when (< size 4) (fail "the TAP file is too short"))
       (let ((offset 0) (blocks 0))
         (loop while (< offset size)
               do (when (< (- size offset) 2)
                    (fail "the TAP file ends inside a block header"))
                  (let ((block (+ (aref bytes offset) (ash (aref bytes (1+ offset)) 8))))
                    (incf offset 2)
                    (when (or (< block 2) (> block (- size offset)))
                      (fail "the TAP file has an invalid block length"))
                    (let ((checksum 0))
                      (loop for index from offset below (+ offset block)
                            do (setf checksum (logxor checksum (aref bytes index))))
                      (unless (zerop checksum)
                        (fail "the TAP file has an invalid block checksum")))
                    (incf offset block) (incf blocks)))
         (when (zerop blocks) (fail "the TAP file contains no blocks"))))
      (:chip8 nil))
    bytes))

(defun file-extension (name)
  (let ((dot (position #\. name :from-end t)))
    (and dot (string-downcase (subseq name dot)))))

(defun little16 (bytes offset)
  (+ (aref bytes offset) (ash (aref bytes (1+ offset)) 8)))

(defun little32 (bytes offset)
  (+ (little16 bytes offset) (ash (little16 bytes (+ offset 2)) 16)))

(defun zip-records (bytes)
  (let ((end (search #(80 75 5 6) bytes :from-end t)))
    (unless (and end (<= (+ end 22) (length bytes))
                 (= (+ end 22 (little16 bytes (+ end 20))) (length bytes))
                 (zerop (little16 bytes (+ end 4)))
                 (zerop (little16 bytes (+ end 6)))
                 (= (little16 bytes (+ end 8)) (little16 bytes (+ end 10))))
      (error "malformed ZIP directory"))
    (let ((count (little16 bytes (+ end 10)))
          (offset (little32 bytes (+ end 16))) (records nil))
      (dotimes (index count (nreverse records))
        (declare (ignore index))
        (unless (and (<= (+ offset 46) (length bytes))
                     (= (little32 bytes offset) #x02014b50))
          (error "malformed ZIP entry"))
        (let* ((name-size (little16 bytes (+ offset 28)))
               (next (+ offset 46 name-size (little16 bytes (+ offset 30))
                        (little16 bytes (+ offset 32)))))
          (unless (<= next (length bytes)) (error "truncated ZIP entry"))
          (unless (and (plusp name-size)
                       (= (aref bytes (+ offset 45 name-size)) (char-code #\/)))
            (push (list (little16 bytes (+ offset 8))
                        (little32 bytes (+ offset 16))
                        (little32 bytes (+ offset 24)))
                  records))
          (setf offset next))))))

(defun crc32 (bytes)
  (let ((checksum (make-instance 'salza2:crc32-checksum)))
    (salza2:update checksum bytes 0 (length bytes))
    (salza2:result checksum)))

(defun zip-encrypted-p (entry)
  (let ((stream (zip::zipfile-entry-stream entry)))
    (file-position stream (zip::zipfile-entry-offset entry))
    (logbitp 0 (zip::file/flags (zip::make-local-header stream)))))

(defclass bounded-zip-output (zip::buffer-output-stream) ())
(defmethod trivial-gray-streams:stream-write-sequence
    ((stream bounded-zip-output) sequence start end &key)
  (when (> (+ (zip::pos stream) (- end start)) (length (zip::buf stream)))
    (fail "the ZIP member could not be read safely"))
  (call-next-method))

(defun zip-entry-data (entry expected-crc)
  (let* ((data (make-array (zip:zipfile-entry-size entry)
                           :element-type '(unsigned-byte 8)))
         (output (make-instance 'bounded-zip-output :buf data)))
    (zip:zipfile-entry-contents entry output)
    (unless (and (= (zip::pos output) (length data))
                 (= (crc32 data) expected-crc))
      (fail "the ZIP member could not be read safely"))
    data))

(defun decode-upload (system filename path)
  (let* ((spec (system-spec system)) (extension (file-extension filename))
         (archive
           (handler-case (read-bytes path 10485760)
             (request-error (condition)
               (if (search "exceeds its size limit" (request-error-message condition))
                   (fail "the upload exceeds 10 MiB")
                   (fail "the upload could not be read")))
             (error () (fail "the upload could not be read")))))
    (when (string= extension (second spec))
      (return-from decode-upload (validate-rom system archive)))
    (unless (string= extension ".zip")
      (fail "choose a ~A file or a ZIP containing one" (second spec)))
    (handler-case
        (let ((records (zip-records archive)))
          (unless (= (length records) 1) (fail "the ZIP must contain exactly one ROM"))
          (destructuring-bind (flags expected-crc expected-size) (first records)
            (let ((stream (flexi-streams:make-in-memory-input-stream archive)))
              (zip::with-zipfile-stream (zip stream)
                (let ((members nil))
                  (maphash (lambda (name entry)
                             (unless (and (plusp (length name))
                                          (char= (char name (1- (length name))) #\/))
                               (push entry members)))
                           (zip:zipfile-entries zip))
                  (unless (= (length members) 1)
                    (fail "the ZIP must contain exactly one ROM"))
                  (let* ((entry (first members)) (name (zip:zipfile-entry-name entry))
                         (mode (zip::zipfile-entry-mode entry)))
                    (when (or (find #\/ name) (find #\\ name) (logbitp 0 flags)
                              (zip-encrypted-p entry)
                              (= (logand mode #o170000) #o120000))
                      (fail "the ZIP contains an unsafe or encrypted member"))
                    (unless (and (string= (file-extension name) (second spec))
                                 (= expected-size (zip:zipfile-entry-size entry))
                                 (<= expected-size (fourth spec)))
                      (fail "the ZIP must contain one ~A file of a valid size" (second spec)))
                    (handler-case
                        (validate-rom system (zip-entry-data entry expected-crc))
                      (request-error (condition) (error condition))
                      (error () (fail "the ZIP member could not be read safely")))))))))
      (request-error (condition) (error condition))
      (error () (fail "the ZIP file is malformed")))))

(defun parse-catalog (path &optional missing-ok)
  (let ((text (read-text path 65536 missing-ok)) (entries nil))
    (unless text (return-from parse-catalog nil))
    (dolist (line (text-lines text) (nreverse entries))
      (setf line (string-right-trim '(#\Return) line))
      (unless (or (string= line "") (char= (char line 0) #\#))
        (let ((fields (split line #\Tab)))
          (unless (= (length fields) 5) (fail "catalog contains a malformed line"))
          (push fields entries)
          (when (> (length entries) 64) (fail "catalog contains too many games")))))))

(defun encode-catalog (entries)
  (with-output-to-string (stream)
    (dolist (entry entries)
      (format stream "~A~C~A~C~A~C~A~C~A~%"
              (first entry) #\Tab (second entry) #\Tab (third entry) #\Tab
              (fourth entry) #\Tab (fifth entry)))))

(defun %add-rom (system title filename path)
  (unless (valid-title-p title)
    (fail "enter a title of 1 through 64 printable characters"))
  (let* ((spec (system-spec system)) (slug (slugify title)))
    (when (string= slug "")
      (fail "the title needs at least one ASCII letter or number for its filename"))
    (let* ((bytes (decode-upload system filename path))
           (base (handler-case (parse-catalog (data-path "nes-deck/menu/games.tsv"))
                   (error (condition) (fail "read built-in catalog: ~A" condition))))
           (uploads (handler-case (parse-catalog (data-path "nes-deck/uploads/games.tsv") t)
                      (error (condition) (fail "read upload catalog: ~A" condition))))
           (identifier (string-right-trim
                        "-" (subseq (format nil "upload-~A-~A" system slug) 0
                                    (min 48 (length (format nil "upload-~A-~A" system slug))))))
           (destination (data-path (format nil "roms/~A/~A~A" system slug (second spec)))))
      (when (>= (+ (length base) (length uploads)) 64) (fail "the menu catalog is full"))
      (dolist (entry (append base uploads))
        (when (or (string= (first entry) identifier)
                  (string= (fourth entry) (namestring destination)))
          (fail "a game with this title is already cataloged")))
      (install-rom destination bytes)
      (let ((entry (list identifier title system (namestring destination) (third spec))))
        (push entry uploads)
        (setf uploads
              (stable-sort uploads
                           (lambda (left right)
                             (if (string= (third left) (third right))
                                 (string< (second left) (second right))
                                 (string< (third left) (third right))))))
        (handler-case
            (atomic-text (data-path "nes-deck/uploads/games.tsv")
                         (encode-catalog uploads))
          (error (condition)
            (uiop:delete-file-if-exists destination)
            (fail "save upload catalog: ~A" condition)))
        (values entry
                (handler-case (progn (restart-dashboard) nil)
                  (error (condition) condition)))))))


(defun add-rom (system title filename path)
  (bordeaux-threads:with-lock-held (*storage-lock*)
    (%add-rom system title filename path)))
