(eval-when (:compile-toplevel :load-toplevel :execute)
  (require 'asdf))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (pushnew :hunchentoot-no-ssl *features*)
  #+sbcl
  (progn (require 'sb-rotate-byte) (require 'sb-bsd-sockets) (require 'sb-posix))
  (asdf:operate 'asdf:load-source-op :hunchentoot)
  (asdf:operate 'asdf:load-source-op :zip))
(defpackage #:retrodeck.uploader
  (:use #:cl)
  (:export #:configure #:start #:stop #:run))
(in-package #:retrodeck.uploader)
(defparameter *source-directory* (uiop:pathname-directory-pathname (or *load-truename* *default-pathname-defaults*)))
(defparameter *data-root* #P"/mnt/data/")
(defparameter *native* "/mnt/data/nes-deck/retrodeck-native")
(defparameter *restart-command* '("/etc/init.d/nes-deck" "restart"))
(defparameter *asset-directory* *source-directory*)
(defparameter *port* 8080)
(defvar *acceptor* nil)
(defvar *storage-lock* (bordeaux-threads:make-lock "uploader storage"))
(defvar *auth-lock* (bordeaux-threads:make-lock "uploader auth"))
(defvar *login-lock* (bordeaux-threads:make-lock "uploader login"))
(defvar *sessions* (make-hash-table :test #'equal))
(defvar *attempts* (make-hash-table :test #'equal))
(defparameter *systems*
  '(("nes" ".nes" "#FF5F00" 8388608 :nes)
    ("gb" ".gb" "#87AF87" 8388608 :gb)
    ("gbc" ".gbc" "#5F87D7" 8388608 :gbc)
    ("zx" ".tap" "#AF87D7" 8388608 :zx)
    ("chip8" ".ch8" "#5FD7D7" 65024 :chip8)))
(defparameter *palette-specs*
  '(("background" . "Background") ("text-dark" . "Dark text")
    ("field" . "Field") ("surface" . "Surface")
    ("inactive-border" . "Inactive border") ("control-border" . "Control border")
    ("footer" . "Footer") ("inactive-text" . "Inactive text")
    ("text" . "Text") ("white" . "Bright white") ("title" . "Title")
    ("volume-off" . "Volume off") ("volume-on" . "Volume on")
    ("selected" . "Selected item") ("wifi-active" . "Wi-Fi active")
    ("wifi-focus" . "Wi-Fi focus") ("wifi-active-border" . "Wi-Fi active border")
    ("field-label" . "Field label") ("accent" . "Accent")
    ("active" . "Active control") ("control-surface" . "Control surface")
    ("muted" . "Muted control")))
(define-condition request-error
    (error)
    ((message :initarg :message :reader request-error-message))
  (:report (lambda (condition stream) (write-string (request-error-message condition) stream))))
(defun fail (control &rest arguments) (error 'request-error :message (apply #'format nil control arguments)))
(defun configure (&key (data-root *data-root*) native (restart-command *restart-command*) (asset-directory *asset-directory*))
  (setf *data-root* (uiop:ensure-directory-pathname data-root)
        *native* (or native (namestring (merge-pathnames "nes-deck/retrodeck-native" *data-root*)))
        *restart-command* restart-command
        *asset-directory* (uiop:ensure-directory-pathname asset-directory)))
(defun data-path (relative) (merge-pathnames relative *data-root*))
(defun split (string character) (uiop:split-string string :separator (list character)))
(defun text-lines (text)
  (let ((lines (split text #\Newline)))
    (if (and lines (string= (car (last lines)) ""))
        (butlast lines)
        lines)))
(defun read-bytes (path maximum &optional missing-ok)
  (unless (probe-file path)
    (if missing-ok
        (return-from read-bytes nil)
        (fail "file is missing: ~A" path)))
  (with-open-file (stream path :direction :input :element-type '(unsigned-byte 8))
    (let ((size (file-length stream)))
      (unless (and size (<= 0 size maximum)) (fail "file exceeds its size limit: ~A" path))
      (let ((bytes (make-array size :element-type '(unsigned-byte 8))))
        (unless (= size (read-sequence bytes stream)) (fail "file could not be read: ~A" path))
        bytes))))
(defun read-text (path maximum &optional missing-ok)
  (let ((bytes (read-bytes path maximum missing-ok)))
    (when bytes (handler-case (babel:octets-to-string bytes :encoding :utf-8)
                  (error () (fail "file is not UTF-8: ~A" path))))))
(defun chmod-private (path) (uiop:run-program (list "chmod" "600" (namestring path))))
(defun atomic-text (path text)
  (ensure-directories-exist path)
  (let* ((directory (uiop:pathname-directory-pathname path))
         (temporary (merge-pathnames (format nil ".uploader-~36R" (random most-positive-fixnum)) directory))
         (installed nil))
    (unwind-protect
         (progn
           (with-open-file (stream temporary :direction :output :if-exists :error
                                            :element-type '(unsigned-byte 8))
             (write-sequence (babel:string-to-octets text :encoding :utf-8) stream))
           (chmod-private temporary)
           (uiop:rename-file-overwriting-target temporary path)
           (setf installed t))
      (unless installed (uiop:delete-file-if-exists temporary)))))
(defun install-rom (path bytes)
  (ensure-directories-exist path)
  (when (probe-file path) (fail "a ROM with this name already exists"))
  (let ((temporary (merge-pathnames (format nil ".rom-upload-~36R" (random most-positive-fixnum))
                                    (uiop:pathname-directory-pathname path)))
        (installed nil))
    (unwind-protect
         (progn
           (with-open-file (stream temporary :direction :output :if-exists :error
                                            :element-type '(unsigned-byte 8))
             (write-sequence bytes stream))
           (chmod-private temporary)
           (when (probe-file path) (fail "a ROM with this name already exists"))
           (rename-file temporary path)
           (setf installed t))
      (unless installed (uiop:delete-file-if-exists temporary)))))
(defun restart-dashboard ()
  (when *restart-command*
    (multiple-value-bind (output ignored status)
        (uiop:run-program *restart-command* :output :string :error-output :output :ignore-error-status t)
      (declare (ignore ignored))
      (unless (zerop status)
        (fail "restart failed with status ~D (~A)" status
              (string-trim '(#\Space #\Tab #\Newline #\Return) output))))))
(defun normalize-rgb (value)
  (when (and (stringp value) (= (length value) 7) (char= (char value 0) #\#)
             (every (lambda (character) (digit-char-p character 16)) (subseq value 1))) (string-upcase value)))
(defun palette-name-p (name) (assoc name *palette-specs* :test #'string=))
(defun valid-legacy-icon-p (value)
  (and (stringp value) (<= 1 (length value) 64)
       (every (lambda (character) (or (char<= #\a character #\z)
                                      (digit-char-p character) (char= character #\-)))
              value)))
(defun validate-palette (values)
  (unless (= (hash-table-count values) (length *palette-specs*)) (fail "palette must contain every dashboard color exactly once"))
  (dolist (spec *palette-specs* values)
    (let ((value (gethash (car spec) values)))
      (unless (and value (string= value (normalize-rgb value))) (fail "palette ~A must use canonical #RRGGBB" (car spec))))))
(defun parse-palette-tsv (text)
  (let ((values (make-hash-table :test #'equal)) (saw-icon nil))
    (dolist (line (text-lines text))
      (let ((fields (split (string-right-trim '(#\Return) line) #\Tab)))
        (unless (= (length fields) 2) (fail "appearance contains a malformed entry"))
        (destructuring-bind
            (name value)
            fields
          (if (string= name "settings-icon")
              (progn (when (or saw-icon (not (valid-legacy-icon-p value))) (fail "appearance contains an invalid settings icon")) (setf saw-icon t))
              (progn (unless (palette-name-p name) (fail "palette contains an unknown entry")) (when (gethash name values) (fail "palette repeats ~A" name)) (setf (gethash name values) (or (normalize-rgb value) (fail "palette ~A is not a full RGB color" name))))))))
    (validate-palette values)))
(defun palette-form (text)
  (handler-case
   (with-input-from-string (stream text)
     (let ((*read-eval* nil) (eof (gensym)))
       (let ((form (read stream nil eof)))
         (unless (and (not (eq form eof)) (eq (read stream nil eof) eof)) (fail "appearance override has an invalid structure"))
         form)))
   (request-error (condition) (error condition)) (error nil (fail "appearance override has an invalid structure"))))
(defun parse-palette-override (text)
  (let* ((form (palette-form text))
         (palette (cond ((and (listp form) (= (length form) 4) (equal (subseq form 0 3) '(:version 2 :palette))) (fourth form)) ((and (listp form) (= (length form) 6) (equal (subseq form 0 3) '(:version 3 :settings-icon)) (valid-legacy-icon-p (fourth form)) (eq (fifth form) :palette)) (sixth form)) (t (fail "appearance override must use schema version 2 or 3"))))
         (values (make-hash-table :test #'equal)))
    (unless (and (listp palette) (= (length palette) (* 2 (length *palette-specs*)))) (fail "palette override has an invalid structure"))
    (loop for (key value) on palette by #'cddr
          for name = (and (keywordp key) (string-downcase (symbol-name key)))
          do (unless (and name (palette-name-p name)) (fail "palette override contains an unknown color")) (when (gethash name values) (fail "palette override repeats ~A" name)) (setf (gethash name values) (or (normalize-rgb value) (fail "palette override ~A is not a full RGB color" name))))
    (validate-palette values)))
(defun current-palette ()
  (let ((base nil) (last-error nil))
    (dolist (path (list (data-path "nes-deck/menu/palette.tsv") (data-path "nes-deck/state/palette.tsv"))) (handler-case (unless base (setf base (parse-palette-tsv (read-text path 4096)))) (error (condition) (setf last-error condition))))
    (unless base (fail "read installed dashboard appearance: ~A" last-error))
    (handler-case
     (let ((override (read-text (data-path "nes-deck/state/dashboard-palette.sexp") 4096 t)))
       (when override (setf base (parse-palette-override override))))
     (error nil nil))
    (mapcar (lambda (spec) (list (car spec) (cdr spec) (gethash (car spec) base))) *palette-specs*)))
(defun encode-palette (values)
  (with-output-to-string (stream)
    (format stream "(:version 2~% :palette~%  (")
    (loop for spec in *palette-specs*
          for index from 0
          do (when (plusp index) (format stream "~%   ")) (format stream ":~A \"~A\"" (car spec) (gethash (car spec) values)))
    (format stream "))~%")))
(defun save-palette (values)
  (bordeaux-threads:with-lock-held (*storage-lock*)
    (validate-palette values)
    (atomic-text (data-path "nes-deck/state/dashboard-palette.sexp") (encode-palette values))
    (handler-case (restart-dashboard) (error (condition) (fail "appearance was saved, but the dashboard could not reload: ~A" condition)))))
(defun system-spec (system) (or (assoc system *systems* :test #'string=) (fail "choose a supported system")))
(defun trim-space-p (character)
  (let ((code (char-code character))) (or (member code '(9 10 11 12 13 32 133 160 5760 8232 8233 8239 8287 12288)) (<= 8192 code 8202))))
(defun valid-title-p (title)
  (and (stringp title) (<= 1 (length title) 64) (not (or (trim-space-p (char title 0)) (trim-space-p (char title (1- (length title))))))
       (every
        (lambda (character)
          (let ((code (char-code character)))
            (not (or (< code 32) (<= 127 code 159)))))
        title)))
(defun slugify (title)
  (string-right-trim "-"
                     (with-output-to-string (stream)
                       (let ((hyphen nil) (size 0))
                         (loop for character across (string-downcase title)
                               while (< size 32)
                               for valid = (or (char<= #\a character #\z) (digit-char-p character))
                               do (cond (valid (write-char character stream) (incf size) (setf hyphen nil)) ((and (plusp size) (not hyphen)) (write-char #\- stream) (incf size) (setf hyphen t))))))))
(defparameter *nintendo-logo* #(206 237 102 102 204 13 0 11 3 115 0 131 0 12 0 13 0 8 17 31 136 137 0 14 220 204 110 230 221 221 217 153 187 187 103 99 110 14 236 204 221 220 153 159 187 185 51 62))
(defun validate-rom (system bytes)
  (let* ((spec (system-spec system)) (size (length bytes)))
    (unless (<= 1 size (fourth spec)) (fail "the ROM must contain 1 through ~D bytes" (fourth spec)))
    (ecase (fifth spec)
      (:nes (unless (and (>= size 16) (equalp (subseq bytes 0 4) #(78 69 83 26))) (fail "the file has no iNES header")))
      ((:gb :gbc)
       (unless (and (>= size 336) (equalp (subseq bytes 260 308) *nintendo-logo*)) (fail "the file has no valid Game Boy header"))
       (let ((checksum 0))
         (loop for index from 308 to 332
               do (setf checksum (mod (- checksum (aref bytes index) 1) 256)))
         (unless (= checksum (aref bytes 333)) (fail "the Game Boy header checksum is invalid")))
       (when (and (eq (fifth spec) :gbc) (not (member (aref bytes 323) '(128 192)))) (fail "the ROM does not advertise Game Boy Color support")))
      (:zx
       (when (< size 4) (fail "the TAP file is too short"))
       (let ((offset 0) (blocks 0))
         (loop while (< offset size)
               do (when (< (- size offset) 2)
                    (fail "the TAP file ends inside a block header")) (let ((block (+ (aref bytes offset) (ash (aref bytes (1+ offset)) 8))))
                                                                        (incf offset 2)
                                                                        (when (or (< block 2) (> block (- size offset))) (fail "the TAP file has an invalid block length"))
                                                                        (let ((checksum 0))
                                                                          (loop for index from offset below (+ offset block)
                                                                                do (setf checksum (logxor checksum (aref bytes index))))
                                                                          (unless (zerop checksum) (fail "the TAP file has an invalid block checksum")))
                                                                        (incf offset block)
                                                                        (incf blocks)))
         (when (zerop blocks) (fail "the TAP file contains no blocks"))))
      (:chip8 nil))
    bytes))
(defun file-extension (name)
  (let ((dot (and (stringp name) (position #\. name :from-end t))))
    (and dot (string-downcase (subseq name dot)))))
(defun little16 (bytes offset) (+ (aref bytes offset) (ash (aref bytes (1+ offset)) 8)))
(defun little32 (bytes offset) (+ (little16 bytes offset) (ash (little16 bytes (+ offset 2)) 16)))
(defun zip-records (bytes)
  (let ((end (search #(80 75 5 6) bytes :from-end t)))
    (unless (and end (<= (+ end 22) (length bytes)) (= (+ end 22 (little16 bytes (+ end 20))) (length bytes)) (zerop (little16 bytes (+ end 4))) (zerop (little16 bytes (+ end 6))) (= (little16 bytes (+ end 8)) (little16 bytes (+ end 10)))) (error "malformed ZIP directory"))
    (let ((count (little16 bytes (+ end 10))) (offset (little32 bytes (+ end 16))) (records nil))
      (dotimes (index count (nreverse records))
        (declare (ignorable index))
        (unless (and (<= (+ offset 46) (length bytes)) (= (little32 bytes offset) #x02014b50)) (error "malformed ZIP entry"))
        (let* ((name-size (little16 bytes (+ offset 28))) (next (+ offset 46 name-size (little16 bytes (+ offset 30)) (little16 bytes (+ offset 32)))))
          (unless (<= next (length bytes)) (error "truncated ZIP entry"))
          (unless (and (plusp name-size) (= (aref bytes (+ offset 45 name-size)) (char-code #\/))) (push (list (little16 bytes (+ offset 8)) (little32 bytes (+ offset 16)) (little32 bytes (+ offset 24))) records))
          (setf offset next))))))
(defun crc32 (bytes)
  (let ((checksum (make-instance 'salza2:crc32-checksum)))
    (salza2:update checksum bytes 0 (length bytes))
    (salza2:result checksum)))
(defun zip-encrypted-p (entry)
  (let ((stream (zip::zipfile-entry-stream entry)))
    (file-position stream (zip::zipfile-entry-offset entry))
    (logbitp 0 (zip::file/flags (zip::make-local-header stream)))))
(defclass bounded-zip-output (zip::buffer-output-stream) nil)
(defmethod trivial-gray-streams:stream-write-sequence ((stream bounded-zip-output) sequence start end &key) (when (> (+ (zip::pos stream) (- end start)) (length (zip::buf stream))) (fail "the ZIP member could not be read safely")) (call-next-method))
(defun zip-entry-data (entry expected-crc)
  (let* ((data (make-array (zip:zipfile-entry-size entry) :element-type '(unsigned-byte 8))) (output (make-instance 'bounded-zip-output :buf data)))
    (zip:zipfile-entry-contents entry output)
    (unless (and (= (zip::pos output) (length data)) (= (crc32 data) expected-crc)) (fail "the ZIP member could not be read safely"))
    data))
(defun decode-upload (system filename path)
  (let* ((spec (system-spec system))
         (extension (file-extension filename))
         (archive
          (handler-case (read-bytes path 10485760)
                        (request-error (condition)
                         (if (search "exceeds its size limit" (request-error-message condition))
                             (fail "the upload exceeds 10 MiB")
                             (fail "the upload could not be read")))
                        (error nil (fail "the upload could not be read")))))
    (when (string= extension (second spec)) (return-from decode-upload (validate-rom system archive)))
    (unless (string= extension ".zip") (fail "choose a ~A file or a ZIP containing one" (second spec)))
    (handler-case
     (let ((records (zip-records archive)))
       (unless (= (length records) 1) (fail "the ZIP must contain exactly one ROM"))
       (destructuring-bind
           (flags expected-crc expected-size)
           (first records)
         (let ((stream (flexi-streams:make-in-memory-input-stream archive)))
           (zip::with-zipfile-stream (zip stream)
             (let ((members nil))
               (maphash (lambda (name entry) (unless (and (plusp (length name)) (char= (char name (1- (length name))) #\/)) (push entry members))) (zip:zipfile-entries zip))
               (unless (= (length members) 1) (fail "the ZIP must contain exactly one ROM"))
               (let* ((entry (first members)) (name (zip:zipfile-entry-name entry)) (mode (zip::zipfile-entry-mode entry)))
                 (when (or (find #\/ name) (find #\\ name) (logbitp 0 flags) (zip-encrypted-p entry) (= (logand mode #o170000) #o120000)) (fail "the ZIP contains an unsafe or encrypted member"))
                 (unless (and (string= (file-extension name) (second spec)) (= expected-size (zip:zipfile-entry-size entry)) (<= expected-size (fourth spec))) (fail "the ZIP must contain one ~A file of a valid size" (second spec)))
                 (handler-case (validate-rom system (zip-entry-data entry expected-crc)) (request-error (condition) (error condition)) (error nil (fail "the ZIP member could not be read safely")))))))))
     (request-error (condition) (error condition)) (error nil (fail "the ZIP file is malformed")))))
(defun parse-catalog (path &optional missing-ok)
  (let ((text (read-text path 65536 missing-ok)) (entries nil))
    (unless text (return-from parse-catalog nil))
    (dolist (line (text-lines text) (nreverse entries))
      (when (> (length (babel:string-to-octets line :encoding :utf-8)) 4095) (fail "bufio.Scanner: token too long")) (setf line (string-right-trim '(#\Return) line))
      (unless (or (string= line "") (char= (char line 0) #\#))
        (let ((fields (split line #\Tab)))
          (unless (= (length fields) 5) (fail "catalog contains a malformed line"))
          (push fields entries)
          (when (> (length entries) 64) (fail "catalog contains too many games")))))))
(defun encode-catalog (entries) (with-output-to-string (stream) (dolist (entry entries) (format stream "~A~C~A~C~A~C~A~C~A~%" (first entry) #\Tab (second entry) #\Tab (third entry) #\Tab (fourth entry) #\Tab (fifth entry)))))
(defun add-rom (system title filename path)
  (bordeaux-threads:with-lock-held (*storage-lock*)
    (unless (valid-title-p title) (fail "enter a title of 1 through 64 printable characters"))
    (let* ((spec (system-spec system)) (slug (slugify title)))
      (when (string= slug "") (fail "the title needs at least one ASCII letter or number for its filename"))
      (let* ((bytes (decode-upload system filename path))
             (base (handler-case (parse-catalog (data-path "nes-deck/menu/games.tsv")) (error (condition) (fail "read built-in catalog: ~A" condition))))
             (uploads (handler-case (parse-catalog (data-path "nes-deck/uploads/games.tsv") t) (error (condition) (fail "read upload catalog: ~A" condition))))
             (raw-id (format nil "upload-~A-~A" system slug))
             (identifier (string-right-trim "-" (subseq raw-id 0 (min 48 (length raw-id)))))
             (destination (data-path (format nil "roms/~A/~A~A" system slug (second spec)))))
        (when (>= (+ (length base) (length uploads)) 64) (fail "the menu catalog is full"))
        (dolist (entry (append base uploads)) (when (or (string= (first entry) identifier) (string= (fourth entry) (namestring destination))) (fail "a game with this title is already cataloged")))
        (install-rom destination bytes)
        (let ((entry (list identifier title system (namestring destination) (third spec))))
          (push entry uploads)
          (setf uploads
                  (stable-sort uploads
                               (lambda (left right)
                                 (if (string= (third left) (third right))
                                     (string< (second left) (second right))
                                     (string< (third left) (third right))))))
          (handler-case (atomic-text (data-path "nes-deck/uploads/games.tsv") (encode-catalog uploads)) (error (condition) (uiop:delete-file-if-exists destination) (fail "save upload catalog: ~A" condition)))
          (values entry (handler-case (progn (restart-dashboard) nil) (error (condition) condition))))))))
(define-condition http-response
    (condition)
    ((body :initarg :body :reader response-body)))
(defun halt (body) (signal 'http-response :body body))
(defun token ()
  (let ((bytes (make-array 32 :element-type '(unsigned-byte 8))))
    (with-open-file (stream "/dev/urandom" :element-type '(unsigned-byte 8)) (unless (= 32 (read-sequence bytes stream)) (error "random token failed")))
    (string-right-trim "." (cl-base64:usb8-array-to-base64-string bytes :uri t))))
(defun same-token-p (left right)
  (and (stringp left) (stringp right) (= (length left) (length right))
       (zerop
        (loop for a across left
              for b across right
              sum (logxor (char-code a) (char-code b))))))
(defun current-session ()
  (let ((cookie (hunchentoot:cookie-in "deck_rom_session")))
    (when (and cookie (= (length cookie) 43))
      (bordeaux-threads:with-lock-held (*auth-lock*)
        (let ((session (gethash cookie *sessions*)))
          (if (and session (> (third session) (get-universal-time)))
              session
              (progn (remhash cookie *sessions*) nil)))))))
(defun create-session ()
  (let* ((now (get-universal-time)) (session (list (token) (token) (+ now 28800))))
    (bordeaux-threads:with-lock-held (*auth-lock*)
      (maphash (lambda (key value) (unless (> (third value) now) (remhash key *sessions*))) *sessions*)
      (setf (gethash (first session) *sessions*) session))
    (hunchentoot:set-cookie "deck_rom_session" :value (first session) :path "/" :http-only t :same-site "Strict" :max-age 28800)
    session))
(defun blocked-seconds (host)
  (bordeaux-threads:with-lock-held (*auth-lock*)
    (let ((attempt (gethash host *attempts*)) (now (get-internal-real-time)))
      (and attempt (> (second attempt) now) (ceiling (- (second attempt) now) internal-time-units-per-second)))))
(defun record-login (host success)
  (bordeaux-threads:with-lock-held (*auth-lock*)
    (if success
        (remhash host *attempts*)
        (progn
         (let* ((now (get-internal-real-time)) (attempt (or (gethash host *attempts*) (list 0 0))))
           (incf (first attempt))
           (when (>= (first attempt) 5)
             (setf (first attempt) 0
                   (second attempt) (+ now (* 300 internal-time-units-per-second))))
           (setf (gethash host *attempts*) attempt))))))
(defun password-valid-p (password) (handler-case (zerop (nth-value 2 (uiop:run-program (list *native* "--verify-uploader-password" (namestring (data-path "nes-deck/uploader/password.conf"))) :input (make-string-input-stream (or password "")) :ignore-error-status t))) (error nil nil)))
(defun plain (status text)
  (setf (hunchentoot:return-code*) status
        (hunchentoot:content-type*) "text/plain; charset=utf-8")
  (format nil "~A~%" text))
(defun html (status body)
  (setf (hunchentoot:return-code*) status
        (hunchentoot:content-type*) "text/html; charset=utf-8")
  body)
(defun security-headers ()
  (dolist
      (header
       '((:cache-control . "no-store") (:content-security-policy . "default-src 'none'; img-src 'self'; style-src 'self'; script-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'") (:cross-origin-opener-policy . "same-origin") (:cross-origin-resource-policy . "same-origin") (:referrer-policy . "no-referrer") (:x-content-type-options . "nosniff") (:x-frame-options . "DENY")))
    (setf (hunchentoot:header-out (car header)) (cdr header))))
(defun host-allowed-p ()
  (let* ((host (hunchentoot:host)) (colon (and host (position #\: host :from-end t))))
    (handler-case
     (and colon (string= (subseq host (1+ colon)) (write-to-string *port*))
          (let* ((address (subseq host 0 colon)) (quad (usocket:dotted-quad-to-vector-quad address)))
            (string= address (usocket:vector-quad-to-dotted-quad quad))))
     (error nil nil))))
(defun same-origin-p ()
  (let ((origin (hunchentoot:header-in* :origin)))
    (or (null origin) (string= origin "null") (string= origin (format nil "http://~A" (hunchentoot:host))))))
(defun media-type-p (expected) (handler-case (multiple-value-bind (type subtype) (hunchentoot::parse-content-type (or (hunchentoot:header-in* :content-type) "")) (string-equal expected (format nil "~A/~A" type subtype))) (error nil nil)))
(defun bounded-content-p (maximum)
  (let ((length (hunchentoot:header-in* :content-length)))
    (and length
         (handler-case
         (let ((value (parse-integer length)))
           (<= 0 value maximum))
         (error nil nil)))))
(defun url-form (maximum)
  (let ((bytes (hunchentoot:raw-post-data :force-binary t)))
    (when (> (length bytes) maximum) (error "form too large"))
    (mapcar
     (lambda (entry)
       (let ((equal (position #\= entry)))
         (cons
          (hunchentoot:url-decode
           (if equal
               (subseq entry 0 equal)
               entry))
          (hunchentoot:url-decode
           (if equal
               (subseq entry (1+ equal))
               "")))))
     (split (babel:octets-to-string bytes :encoding :utf-8) #\&))))
(defparameter *page-head*
  "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"robots\" content=\"noindex, nofollow\"><title>Retro Deck ROM uploader</title><link rel=\"stylesheet\" href=\"/assets/paper.css\"><script src=\"/assets/palette.js\" defer></script></head><body><a class=\"skip-link\" href=\"#main-content\">Skip to content</a><main id=\"main-content\"><header><h1>ROM uploader</h1>")
(defparameter *upload-form*
  "<form action=\"/upload\" method=\"post\" enctype=\"multipart/form-data\"><input type=\"hidden\" name=\"csrf\" value=\"~A\"><label><span>Console</span><select name=\"system\" required><option value=\"nes\">NES</option><option value=\"gb\">Game Boy</option><option value=\"gbc\">Game Boy Color</option><option value=\"zx\">ZX Spectrum</option><option value=\"chip8\">CHIP-8</option></select></label><label><span>Game name</span><input type=\"text\" name=\"title\" minlength=\"1\" maxlength=\"64\" autocomplete=\"off\" required></label><label><span>ROM or ZIP</span><input type=\"file\" name=\"rom\" accept=\".nes,.gb,.gbc,.tap,.ch8,.zip\" required></label><button type=\"submit\" class=\"primary-button\">Upload game</button></form>")
(defparameter *login-form* "<form action=\"/login\" method=\"post\"><label><span>Password</span><input type=\"password\" name=\"password\" minlength=\"8\" maxlength=\"128\" autocomplete=\"current-password\" required autofocus></label><button type=\"submit\" class=\"primary-button\">Sign in</button></form>")
(defun page (session &key error notice palette)
  (flet ((escape (value)
           (hunchentoot:escape-for-html value)))
    (with-output-to-string (stream)
      (write-string *page-head* stream)
      (when session (format stream "<form action=\"/logout\" method=\"post\"><input type=\"hidden\" name=\"csrf\" value=\"~A\"><button type=\"submit\" class=\"quiet-button\">Sign out</button></form>" (second session)))
      (write-string "</header>" stream)
      (if (null session)
          (progn (when error (format stream "<p class=\"message error\" role=\"alert\"><strong>Error:</strong> ~A</p>" (escape error))) (write-string *login-form* stream))
          (progn
           (when error (format stream "<p class=\"message error\" role=\"alert\"><strong>Not filed:</strong> ~A</p>" (escape error)))
           (when notice (format stream "<p class=\"message\" role=\"status\"><strong>Filed:</strong> ~A</p>" (escape notice)))
           (format stream *upload-form* (second session))
           (when palette
             (format stream "<section class=\"palette-section\"><h2>Dashboard appearance</h2><form action=\"/palette\" method=\"post\"><input type=\"hidden\" name=\"csrf\" value=\"~A\"><h3>Colors</h3><p class=\"hint\">#RRGGBB</p><div class=\"palette-grid\">" (second session))
             (dolist (field palette)
               (destructuring-bind
                   (name label value)
                   field
                 (format stream
                         "<label><span>~A</span><span class=\"palette-inputs\"><input class=\"palette-picker\" type=\"color\" value=\"~A\" data-palette-picker=\"palette-~A\" aria-label=\"Choose ~A\"><input class=\"palette-hex\" id=\"palette-~A\" type=\"text\" name=\"~A\" value=\"~A\" pattern=\"#[0-9A-Fa-f]{6}\" minlength=\"7\" maxlength=\"7\" spellcheck=\"false\" autocomplete=\"off\" required></span></label>"
                         label value name label name name value)))
             (write-string "</div><button type=\"submit\" class=\"primary-button\">Apply appearance</button></form></section>" stream))))
      (write-string "</main></body></html>" stream))))
(defun dashboard (session &optional error notice)
  (let ((message error) palette)
    (handler-case (parse-catalog (data-path "nes-deck/uploads/games.tsv") t) (error nil (unless message (setf message "The upload catalog cannot be read."))))
    (handler-case (setf palette (current-palette)) (error nil (unless message (setf message "The dashboard appearance cannot be read."))))
    (page session :error message :notice notice :palette palette)))
(defun require-change (unauthenticated-status)
  (unless (and (eq (hunchentoot:request-method*) :post) (same-origin-p)) (halt (plain 403 "Request rejected")))
  (or (current-session)
      (halt
       (plain unauthenticated-status
              (if (= unauthenticated-status 401)
                  "Authentication required"
                  "Request rejected")))))
(defun index-route ()
  (unless (eq (hunchentoot:request-method*) :get) (setf (hunchentoot:header-out :allow) "GET") (halt (plain 405 "Method not allowed")))
  (let ((session (current-session)))
    (html 200
          (if session
              (dashboard session)
              (page nil)))))
(defun login-route ()
  (unless (eq (hunchentoot:request-method*) :post) (setf (hunchentoot:header-out :allow) "POST") (halt (plain 405 "Method not allowed")))
  (unless (same-origin-p) (halt (plain 403 "Cross-origin request rejected")))
  (unless (media-type-p "application/x-www-form-urlencoded") (halt (plain 415 "Unsupported form encoding")))
  (let ((form (handler-case (and (bounded-content-p 512) (url-form 512)) (error nil nil))) (host (hunchentoot:remote-addr*)))
    (unless form (halt (html 400 (page nil :error "The login form was malformed."))))
    (labels ((reject-blocked ()
               (let ((seconds (blocked-seconds host)))
                 (when seconds (setf (hunchentoot:header-out :retry-after) (write-to-string seconds)) (halt (html 429 (page nil :error "Too many attempts. Wait five minutes before trying again.")))))))
      (reject-blocked)
      (unless
          (loop repeat 200
                when (bordeaux-threads:acquire-lock *login-lock* nil) return t
                do (sleep 0.01))
        (setf (hunchentoot:header-out :retry-after) "3")
        (halt (html 429 (page nil :error "Another sign-in is being checked. Try again in a moment."))))
      (unwind-protect
          (progn
           (reject-blocked)
           (let ((success (password-valid-p (cdr (assoc "password" form :test #'string=)))))
             (record-login host success)
             (unless success (halt (html 401 (page nil :error "That password was not accepted."))))
             (create-session)
             (hunchentoot:redirect "/" :code 303)))
        (bordeaux-threads:release-lock *login-lock*)))))
(defun logout-route ()
  (let ((session (require-change 403)))
    (unless (same-token-p (hunchentoot:post-parameter "csrf") (second session)) (halt (plain 403 "Request rejected")))
    (bordeaux-threads:with-lock-held (*auth-lock*)
      (remhash (first session) *sessions*))
    (hunchentoot:set-cookie "deck_rom_session" :value "" :path "/" :http-only t :same-site "Strict" :max-age -1)
    (hunchentoot:redirect "/" :code 303)))
(defun upload-route ()
  (let ((session (require-change 401)))
    (unless (and (bounded-content-p 12582912) (media-type-p "multipart/form-data")) (halt (html 400 (dashboard session "The upload form was malformed or too large."))))
    (let ((form (handler-case (hunchentoot:post-parameters*) (error nil nil))))
      (unless form (halt (html 400 (dashboard session "The upload form was malformed or too large."))))
      (unless (same-token-p (cdr (assoc "csrf" form :test #'string=)) (second session)) (halt (plain 403 "Request rejected")))
      (let ((files
             (loop for (name . value) in form
                   when (and (string= name "rom") (listp value) (pathnamep (first value)))
                   collect value)))
        (unless (= (length files) 1) (halt (html 400 (dashboard session "Choose exactly one ROM or single-ROM ZIP."))))
        (destructuring-bind
            (path filename type)
            (first files)
          (declare (ignore type))
          (unless (probe-file path) (halt (html 400 (dashboard session "The uploaded file could not be opened."))))
          (handler-case
           (multiple-value-bind (entry restart-error)
               (add-rom (cdr (assoc "system" form :test #'string=)) (cdr (assoc "title" form :test #'string=)) filename path)
             (html 200
                   (dashboard session nil
                              (format nil
                                      (if restart-error
                                          "~A was saved. The dashboard will pick it up after its next restart."
                                          "~A was validated, filed, and added to the dashboard.")
                                      (second entry)))))
           (request-error (condition) (html 422 (dashboard session (request-error-message condition)))) (error (condition) (html 422 (dashboard session (princ-to-string condition))))))))))
(defun palette-route ()
  (let ((session (require-change 401)))
    (unless (media-type-p "application/x-www-form-urlencoded") (halt (plain 415 "Unsupported form encoding")))
    (let ((form (handler-case (and (bounded-content-p 4096) (url-form 4096)) (error nil nil))))
      (unless form (halt (html 400 (dashboard session "The appearance form was malformed."))))
      (unless (and (= 1 (count "csrf" form :key #'car :test #'string=)) (same-token-p (cdr (assoc "csrf" form :test #'string=)) (second session))) (halt (plain 403 "Request rejected")))
      (let ((values (make-hash-table :test #'equal)))
        (dolist (field form)
          (unless (string= (car field) "csrf") (unless (and (palette-name-p (car field)) (null (gethash (car field) values))) (halt (html 400 (dashboard session "The appearance form contains an unknown or repeated field.")))) (setf (gethash (car field) values) (or (normalize-rgb (cdr field)) (halt (html 400 (dashboard session "Every color must be a full RGB value like #12ABEF.")))))))
        (handler-case (progn (save-palette values) (html 200 (dashboard session nil "Dashboard appearance was saved and applied."))) (request-error (condition) (html 422 (dashboard session (request-error-message condition)))) (error (condition) (html 422 (dashboard session (princ-to-string condition)))))))))
(defun asset-route (name type)
  (unless (eq (hunchentoot:request-method*) :get) (halt (plain 405 "Method not allowed")))
  (setf (hunchentoot:return-code*) 200
        (hunchentoot:content-type*) type)
  (read-text (merge-pathnames name *asset-directory*) 65536))
(defun dispatch ()
  (handler-case
   (progn
    (security-headers)
    (unless (host-allowed-p) (halt (plain 421 "Use one of this Deck's IPv4 addresses on port 8080.")))
    (let ((path (hunchentoot:script-name*)))
      (cond ((string= path "/") (index-route)) ((string= path "/login") (login-route)) ((string= path "/logout") (logout-route)) ((string= path "/upload") (upload-route)) ((string= path "/palette") (palette-route)) ((string= path "/assets/paper.css") (asset-route "uploader-paper.css" "text/css; charset=utf-8"))
            ((string= path "/assets/palette.js") (asset-route "uploader-palette.js" "text/javascript; charset=utf-8")) (t (plain 404 "404 page not found")))))
   (http-response (response) (response-body response))))
(defclass blocking-acceptor (hunchentoot:easy-acceptor) nil)
#+ecl
(defmethod hunchentoot:accept-connections ((acceptor blocking-acceptor))
  (usocket:with-server-socket (listener (hunchentoot::acceptor-listen-socket acceptor))
    (loop
     (bordeaux-threads:with-lock-held ((hunchentoot::acceptor-shutdown-lock acceptor))
       (when (hunchentoot::acceptor-shutdown-p acceptor) (return)))
     (let ((client (handler-case (usocket:socket-accept listener) (usocket:connection-aborted-error nil nil))))
       (when client (hunchentoot::set-timeouts client (hunchentoot:acceptor-read-timeout acceptor) (hunchentoot:acceptor-write-timeout acceptor)) (hunchentoot:handle-incoming-connection (hunchentoot::acceptor-taskmaster acceptor) client))))))
(defun start (&key (address "0.0.0.0") (port 8080) (data-root *data-root*) native (restart-command *restart-command*) (asset-directory *asset-directory*))
  (when *acceptor* (error "uploader is already running"))
  (configure :data-root data-root :native native :restart-command restart-command :asset-directory asset-directory)
  (setf *port* port
        hunchentoot:*show-lisp-errors-p* nil
        hunchentoot:*dispatch-table* (list (hunchentoot:create-prefix-dispatcher "/" #'dispatch))
        *acceptor* (make-instance 'blocking-acceptor :address address :port port :read-timeout 35 :write-timeout 35))
  (clrhash *sessions*)
  (clrhash *attempts*)
  (hunchentoot:start *acceptor*))
(defun stop () (when *acceptor* (hunchentoot:stop *acceptor*) (setf *acceptor* nil)))
(defun run (&rest arguments) (unwind-protect (progn (apply #'start arguments) (loop (sleep 3600))) (stop)))
